-- V1: Schema inicial da aplicação.
--
-- Escrito em SQL padrão (ANSI), compatível tanto com H2 (usado em
-- desenvolvimento) quanto com PostgreSQL (usado em produção/AWS). Evite
-- sintaxe específica de um único banco em migrations futuras, a menos que
-- seja estritamente necessário.
--
-- As colunas e tipos aqui espelham exatamente as entidades JPA em
-- com.rodrigolimeira.tatamemanager.model — se você alterar uma entidade,
-- crie uma NOVA migration (V2__..., V3__...) em vez de editar esta.
-- Migrations já aplicadas nunca devem ser modificadas.

-- Todas as tabelas usam "IF NOT EXISTS" de propósito: isso deixa a migration segura
-- tanto num banco 100% vazio (RDS novo na AWS) quanto num banco de dev local que já
-- tinha alunos/configuracoes/pagamentos criados pelo antigo "ddl-auto=update" (antes
-- do Flyway existir no projeto) - nesse caso só a tabela "usuarios", que é nova, é
-- efetivamente criada. Se preferir começar 100% do zero localmente, é só apagar o
-- arquivo do H2 (ex.: banco_tatame.mv.db) antes de subir a aplicação.

-- ---------------------------------------------------------------------
-- usuarios: login do app (ADMIN / OPERADOR) usado para autenticação JWT
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS usuarios (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(100) NOT NULL,
    senha_hash  VARCHAR(255) NOT NULL,
    role        VARCHAR(20)  NOT NULL,
    ativo       BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_usuarios_username UNIQUE (username)
);

-- ---------------------------------------------------------------------
-- alunos: cadastro dos atletas
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS alunos (
    cpf                 VARCHAR(11)  NOT NULL PRIMARY KEY,
    nome_completo        VARCHAR(255) NOT NULL,
    celular              VARCHAR(20)  NOT NULL,
    idade                INTEGER      NOT NULL,
    dia_vencimento       INTEGER      NOT NULL,
    ultimo_pagamento     DATE,
    ativo                BOOLEAN      NOT NULL DEFAULT TRUE,
    data_ultimo_aviso    DATE,
    data_matricula       DATE,
    tipo_matricula       VARCHAR(20)  NOT NULL DEFAULT 'VETERANO'
);

-- ---------------------------------------------------------------------
-- pagamentos: histórico de pagamentos de cada aluno (1 linha por pagamento)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pagamentos (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_cpf      VARCHAR(11)      NOT NULL,
    data_pagamento DATE             NOT NULL,
    valor          DOUBLE PRECISION NOT NULL,
    CONSTRAINT fk_pagamentos_aluno FOREIGN KEY (aluno_cpf) REFERENCES alunos (cpf)
);

CREATE INDEX IF NOT EXISTS idx_pagamentos_aluno_cpf ON pagamentos (aluno_cpf);

-- ---------------------------------------------------------------------
-- configuracoes: tabela de 1 linha só (id fixo = 1) com valores de mensalidade
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS configuracoes (
    id                          BIGINT           NOT NULL PRIMARY KEY,
    valor_mensalidade_novato    DOUBLE PRECISION NOT NULL,
    valor_mensalidade_veterano  DOUBLE PRECISION NOT NULL
);
